Blog/apps/views/blog.py
#-*-codeing=utf-8 -*-
#@Time :2021/9/15 19:11
#@Author :Csn
#@File:blog
#@Software:PyCharm
#关于网页博客相关的功能函数
from  flask import Blueprint,request,session,redirect,url_for,render_template
import urlpath
from apps.models.blogmodels import User,Blog,Like
from exts import db
from sqlalchemy import or_
blog_bp=Blueprint('blog',__name__,url_prefix='/blog')

#1发布博客
@blog_bp.route('/publish/',methods=['GET','POST'])
def publish():
    if request.method=='GET':
        if session.get('username'):
            return render_template('publish.html')
        else:
            urlpath.current_url=url_for('blog.publish')
            return redirect(url_for('user.login'))
    else:
        print(request.form)
        user=User.query.filter(User.username==session.get('username')).first()
        title=request.form.get('title')
        content=request.form.get('content')
        blog=Blog(title,content,user.uid)
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('index'))

@blog_bp.route('/index/')
def blogindex():
    #查询所有博客
    blogs=Blog.query.all()

    return render_template('index.html',blogs=blogs)
@blog_bp.route('/newindex/')
def blognewindex():
    #查询所有博客

    #blogs=Blog.query.all()
    # 分页
    curpage = int(request.args.get('curpage', 1))
    paginate = Blog.query.paginate(page=curpage, per_page=3)

    if session.get('username'):
        user=User.query.filter(User.username==session.get('username')).first()
        like_bids=[blog.bid for blog in user.like_blogs ]
        return render_template('new_index.html',paginate=paginate,like_bids=like_bids)

    else:
        like_bids=int('')
        return render_template('new_index.html',paginate=paginate,like_bids=like_bids)
@blog_bp.route('/like/')
def like():
    if session.get('username'):

        user=User.query.filter(User.username==session.get('username')).first()
        bid=int(request.args.get('bid'))
        blog=Blog.query.get(bid)
        like=Like(user.uid,bid)

        db.session.add(like)
        db.session.commit()
        return redirect(url_for('blog.blogindex'))
    else:
        urlpath.current_url=url_for('blog.blogindex')
        return redirect(url_for('user.login'))
@blog_bp.route('/unlike/')
def unlike():
    user = User.query.filter(User.username == session.get('username')).first()
    bid = int(request.args.get('bid'))
    blog = Blog.query.get(bid)
    like=Like.query.filter(Like.bid==bid,Like.uid==user.uid).first()
    db.session.delete(like)
    db.session.commit()
    return redirect(url_for('blog.blogindex'))

#点赞，取消点赞请求
@blog_bp.route('/likeorunlike/')
def likeorunlike():
    # if session.get('username'):
        bid=int(request.args.get('bid'))
        blog = Blog.query.get(bid)
        user = User.query.filter(User.username == session.get('username')).first()
        flag=False

        for like_user in blog.like_users:
            if like_user.username==session.get('username'):
                #取消点赞
                flag=True

                break
        if flag is True:
            # 取消点赞
            like=Like.query.filter(Like.uid==user.uid,Like.bid==bid).first()
            db.session.delete(like)
            db.session.commit()
            return {'code': 201, 'likenum': len(blog.like_users)}
        else:
            #d点赞
            like=Like(user.uid,bid)
            db.session.add(like)
            db.session.commit()
        # return redirect(url_for('blog.blognewindex'))
            return {'code':200,'likenum':len(blog.like_users)}

    # else:
    #     urlpath.current_url = url_for('blog.blogindex')
    #     return redirect(url_for('user.login'))

#点击用户名进入对应主页
@blog_bp.route('/userindex/')
def userindex():
    username=request.args.get('name')
    user=User.query.filter(User.username==username).first()


    return render_template('userindex.html',blogs=user.blogs)
#搜索博客
@blog_bp.route('/search/')
def search():
    search_content=request.args.get('search')

    blogs=Blog.query.filter(or_(Blog.title.contains(search_content),Blog.content.contains(search_content))).all()


    return render_template('search.html',blogs=blogs)

#sc删除博客
@blog_bp.route('/deleteblog',methods=['POST'])
def deleteblog():
    bid=int(request.form.get('bid'))
    blog=Blog.query.get(bid)
    db.session.delete(blog)
    db.session.commit()
    return '删除成功'

Blog/apps/views/user.py
#-*-codeing=utf-8 -*-
#@Time :2021/9/9 21:35
#@Author :Csn
#@File:user
#@Software:PyCharm
import os
import uuid
import basepath
from apps.models.blogmodels import User
from flask import Blueprint,request,render_template,redirect,url_for,session
from exts import db
import urlpath
user_bp=Blueprint('user',__name__,url_prefix='/user')
#关于网页 注册登录等 功能函数

#注册
@user_bp.route('/register/',methods=['GET','POST'])
def register():
    if request.method=='GET':
        return render_template('register.html')
    else:
        name=request.form.get('username')
        psw=request.form.get('psw')
        phone=request.form.get('phone')

        user=User(name,psw,phone)
        db.session.add(user)
        db.session.commit()
        print(f'{request.form}')
        return redirect(url_for('user.login'))
@user_bp.route('/checkname/',methods=['POST'])
#检验用户名是否存在
def check_name():
    print(request.form)
    username=request.form.get('username')
    data=User.query.filter(User.username==username).first()
    print(data)
    if data:
        return {'code':2000,'msg':'用户名已存在'}
    else:
        return {'code': 2001, 'msg': '用户名不存在'}
    #无效代码
    return 'ok'

@user_bp.route('/checkphone/',methods=['POST'])
def check_phone():
    print(request.form)
    phone = request.form.get('phone')
    data = User.query.filter(User.phone == phone).first()
    print(phone)
    print(data)
    print(len(phone))
    if len(phone)!=11:
        return {'code': 2003, 'msg': '请输入正确的手机号'}
    else:
        if data:
            return {'code': 2003, 'msg': '手机号已注册'}
        else:
            return {'code': 2004, 'msg': '手机号没注册'}
@user_bp.route('/login/',methods=['GET','POST'])
def login():
    if request.method=='GET':
        return render_template('login.html',message='')
    else:
        username = request.form.get('username')
        psw = request.form.get('psw')
        user=User.query.filter(User.username==username,User.password==psw).first()
        if user is None:
            return render_template('login.html',message='用户名或者密码错误')
        else:
            #保存用户信息
            session['username']=username
            # session['user']=user
            print(session)
            return redirect(urlpath.current_url)

        return '登录成功'

@user_bp.route('/exit/')
def exit():
    session.pop('username')
    return redirect(url_for('index'))


#修改头像
@user_bp.route('/updateicon/',methods=['GET','POST'])
def updateicon():
    if request.method=='GET':
        return render_template('updateicon.html')
    else:
        icon_file=request.files.get('icon')
        if icon_file.filename !='':
            image_id=uuid.uuid4()
            dot_pos=icon_file.filename.rfind('.')
            image_name=str(image_id)+icon_file.filename[dot_pos:]
            save_path=os.path.join(basepath.basedir,'static\icon',image_name)
            icon_file.save(save_path)

            user=User.query.filter(User.username==session.get('username')).first()
            user.user_icon='icon/'+image_name
            db.session.commit()
        return redirect(url_for('blog.blogindex'))

Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>

    <!--/* 网页基础模板建立 父模板 */ -->
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    {%  block css %} {% endblock %}
</head>
<body>
        <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Python博客</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav" select >
            <li ><a href="{{ url_for('blog.blogindex') }}">首页 <span class="sr-only">(current)</span></a></li>
            <li><a href="{{url_for('blog.publish')}}">发布博客</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">发布博客（新） <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{url_for('blog.blognewindex')}}">发布新博客</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" action="{{url_for('blog.search')}}">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="请输入搜索内容" name="search">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
            {#判断#}
          {%if session.get('username') %}
              <ul class="nav navbar-nav navbar-right">
                {#<li><img src="{{url_for('static', filename='icon/LenovoWallPaper.jpg')}}" width="40px"></li>#}
<!--                <li><a href="{{url_for('user.login')}}">欢迎{{session.get('username')}}</a></li>-->
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">欢迎{{session.get('username')}} <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="#">修改用户名</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li><a href="{{url_for('user.updateicon')}}">修改头像</a></li>

                          </ul>
                      </li>
                <li><a href="{{ url_for('user.exit') }}">退出登录</a></li>
              </ul>
          {% else %}
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{{url_for('user.login')}}">登录</a></li>
                <li><a href="{{ url_for('user.register') }}">注册</a></li>
              </ul>
           {%endif%}
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    {% block body %}{% endblock %}

    {% block js %}
        <script>
            $('.select>li').click(function () {
                $('.select>li').attr('class','')

                $(this).attr('class','active')
            })
        </script>
    {% endblock %}
</body>
</html>

Blog/templates/index.html
{%  extends 'base.html'  %}


{% block title %}首页{% endblock %}

{% block css%}
    <style>
        .box{
            border-radius: 10px;
            border: 1px solid gray;
            margin-bottom: 10px;
            padding: 10px 30px;
        }
        .thum{
            font-size: 20px;
        }
        .user{
            float: left;
        }
        .like{
            float: right;
            cursor: pointer;

        }
        .clear{
            clear: both;
        }
    </style>
{% endblock %}

{%block body %}
<div class="container">

    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
    {% if blogs %}

        {% for blog in blogs %}
            {% set islike={'flag':False} %}
            {%for user in blog.like_users%}
                {%if session.get('username')==user.username %}
                    {%if islike.update({'flag':True})%} {%endif%}
                {%endif%}
            {%endfor%}
            <div class="box">
                <h2 class="title">
                    <a href="#">{{blog.title}}</a>
                </h2>
                <p class="thum">{{blog.thum_content}}</p>
                <div class="user_like">
                    <div class="user">
<!--                         url_for('static', filename='icon/LenovoWallPaper.jpg')-->
                        <a href="{{url_for('blog.userindex')}}?name={{blog.user.username}}">
                            {%if blog.user.user_icon %}
                             <img src="{{url_for('static', filename=blog.user.user_icon)}}" width="30px">
                            {%else%}
                             <img src="{{url_for('static', filename='icon/LenovoWallPaper.jpg')}}" width="30px">
                            {%endif%}
                             <span>作者：{{blog.user.username}}</span>
                        </a>
                    </div>
                    {%if islike.flag %}
                        <div class="like" bid="{{blog.bid}}">
                           <a href="{{url_for('blog.unlike')}}?bid={{blog.bid}}">
                                <span class="glyphicon glyphicon-thumbs-up" style="color: red"></span>
                            {#点赞的数量，点赞的用户个数 |length #}
                                <span >{{blog.like_users|length}}</span>
                           </a>
                        </div>
                    {%else%}
                        <div class="like" bid="{{blog.bid}}">
                           <a href="{{url_for('blog.like')}}?bid={{blog.bid}}">
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                            {#点赞的数量，点赞的用户个数 |length #}
                                <span >{{blog.like_users|length}}</span>
                           </a>
                        </div>
                    {%endif%}
                </div>
                <div class="clear"></div>
            </div>
        {% endfor %}

    {% else %}
       <h3>还没有人发表博客</h3>
    {% endif %}
</div>
{%endblock%}

{% block js %}
<!--    <script>-->
<!--        $('.like').click(function () {-->
<!--            $.ajax({-->
<!--                url:"{{url_for('blog.like')}}",-->
<!--                type:'post',-->
<!--                data:'bid='+$('.like').attr('bid')+"&csrf_token="+$('.csrf_token').val(),-->
<!--                success: function (result,statue) {-->
<!--                    console.log(result);-->
<!--                }-->
<!--            })-->
<!--        })-->
<!--    </script>-->
{% endblock %}

Blog/templates/login.html
{%  extends 'base.html'  %}


{% block title %}登录{% endblock %}

{% block body %}
    <div class="container">
        <form class="form-horizontal" method="post" action="{{url_for('user.login')}}">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
          <div class="form-group">
            <label for="inputname" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="inputname" placeholder="请输入用户名" name="username" required>
              <p style="color:red;display: none" class="message"></p>
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword" placeholder="请输入密码" name="psw" required>
                <span style="color: red">{{message}}</span>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="login" class="btn btn-default register" >登录</button>
            </div>
          </div>
        </form>
    </div>
{% endblock %}

{% block js %}

{%  endblock %}

Blog/templates/new_index.html
{%  extends 'base.html'  %}


{% block title %}新首页{% endblock %}

{% block css%}
    <style>
        .box{
            border-radius: 10px;
            border: 1px solid gray;
            margin-bottom: 10px;
            padding: 10px 30px;
        }
        .thum{
            font-size: 20px;
        }
        .user{
            float: left;
        }
        .like{
            float: right;
            cursor: pointer;

        }
        .clear{
            clear: both;
        }
    </style>
{% endblock %}

{%block body %}
<div class="container">

    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
    {% if paginate %}

        {% for blog in paginate.items %}

            <div class="box">
                <h2 class="title">
                    <a href="#">{{blog.title}}</a>
                </h2>
                <p class="thum">{{blog.thum_content}}</p>
                <div class="user_like">
                    <a href="{{url_for('blog.userindex')}}?name={{blog.user.username}}">
                        <div class="user">
                         <span>用户名：{{blog.user.username}}</span>
                        </div>
                    </a>

                    <div class="like"  >
                        {%if session.get('username')==blog.user.username%}
                            <a class="delete" bid="{{blog.bid}}">删除</a>
                        {%endif%}
                        {%if session.get('username')%}
<!--                            <a href="{{url_for('blog.likeorunlike')}}?bid={{blog.bid}}">-->
                            <a class="likea" bid="{{blog.bid}}" style="color: gray">
                        {%else%}
                            <a href="{{url_for('user.login')}}"    ></a>
                        {%endif%}

                           {%if blog.bid in like_bids %}
                            <span class="glyphicon glyphicon-thumbs-up likehand" style="color: red"></span>
                           {%else%}
                            <span class="glyphicon glyphicon-thumbs-up likehand" ></span>
                           {%endif%}
                        {#点赞的数量，点赞的用户个数 |length #}
                            <span class="likenum">{{blog.like_users|length}}</span>
                       </a>
                    </div>

                </div>
                <div class="clear"></div>

            </div>

        {% endfor %}
    <ul class="pagination">
        {%if paginate.has_prev %}
            <li><a href="{{url_for('blog.blognewindex')}}?curpage={{paginate.prev_num}}">&laquo;</a></li>
        {%else%}
<!--            <li class="disabled"><a href="#">&laquo;</a></li>-->
        {%endif%}
        {%for pagenum in paginate.iter_pages()%}
            <li {%if pagenum==paginate.page%}class="active"{%endif%}><a href="{{url_for('blog.blognewindex')}}?curpage={{pagenum}}">{{pagenum}}</a> </li>
        {%endfor%}
        {%if paginate.has_next %}
            <li><a href="{{url_for('blog.blognewindex')}}?curpage={{paginate.next_num}}">&raquo;</a></li>
        {%else%}
<!--            <li class="disabled"><a href="#">&laquo;</a></li>-->
        {%endif%}

    </ul>
    {% else %}
       <h3>还没有人发表博客</h3>
    {% endif %}
</div>
{%endblock%}

{% block js %}
    <script>
        $('.likea').click(function () {
            // #局部刷新点赞
            var _this=$(this)
            $.ajax({
                url:"{{url_for('blog.likeorunlike')}}",
                type:'get',
                data:'bid='+_this.attr('bid'),
                success: function (result,status) {
                    if(status=='success'){
                        _this.find('.likenum').text(result.likenum)
                        if(result.code==200){
                            _this.find('.likehand').css('color','red')

                        }else {
                             _this.find('.likehand').css('color','gray')
                        }
                    }

                }
            })
        })
        $('.delete').click(function () {
              var _this=$(this)
            $.ajax({
                url:"{{url_for('blog.deleteblog')}}",
                type:'post',
                data:"bid="+_this.attr('bid')+'&csrf_token='+"{{csrf_token()}}",
                success:function (result,status) {
                    console.log(result)
                    if(status=='success'){
                        _this.parent().parent().parent().remove()
                    }
                }
            })
        })
    </script>
<!--    <script>-->
<!--        $('.like').click(function () {-->
<!--            $.ajax({-->
<!--                url:"{{url_for('blog.like')}}",-->
<!--                type:'post',-->
<!--                data:'bid='+$('.like').attr('bid')+"&csrf_token="+$('.csrf_token').val(),-->
<!--                success: function (result,statue) {-->
<!--                    console.log(result);-->
<!--                }-->
<!--            })-->
<!--        })-->
<!--    </script>-->
{% endblock %}

Blog/templates/register.html
{%  extends 'base.html'  %}


{% block title %}注册{% endblock %}

{% block body %}
    <div class="container">
        <form class="form-horizontal" method="post" action="{{url_for('user.register')}}">

          <input type="hidden" class="csrf_token" name="csrf_token" value="{{csrf_token()}}"/>
          <div class="form-group">
            <label for="inputname" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="inputname" placeholder="请输入用户名" name="username" required>
              <p style="color:red;display: none" class="message"></p>
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword" placeholder="请输入密码" name="psw" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword1" class="col-sm-2 control-label">确认密码</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" id="inputPassword1" placeholder="请再次输入密码" name="againpsw" required>
              <span class="pswmsg" style="color: red;display: none">两次密码不一致</span>
            </div>
          </div>
          <div class="form-group">
            <label for="inputPhone" class="col-sm-2 control-label">手机号</label>
            <div class="col-sm-10" >
              <input type="text" class="form-control"  id="inputPhone" placeholder="请输入手机号" name="phone" required>
              <p style="color: red;display: none" class="phonemess"></p>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default register" >注册</button>
            </div>
          </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
      {#判断用户名#}
      $('#inputname').blur(function () {
        //{#  发送请求，判断用户名是否存在
          //#}
          $.ajax({
              //设置请求的路由
              url:"{{ url_for('user.check_name')}}",
              type:'post',
              data:"username="+$('#inputname').val()+'&csrf_token='+$('.csrf_token').val(),
              success:function(result,status) {
                 console.log(result)
                 if(result.code==2000){
                   $('.message').css('display','block')
                   $('.message').text(result.msg)
                   {#注册按钮灰色#}
                   $('.register').prop('disabled',true)
                 }else {
                   $('.message').css('display','none')
                   $('.register').prop('disabled',false)
                 }
              }
          })

      })
      {#判断手机号#}
      $('#inputPhone').blur(function () {
          $.ajax({
             url:"{{ url_for('user.check_phone')}}",
              type:'post',
              data:"phone="+$('#inputPhone').val()+'&csrf_token='+$('.csrf_token').val(),
              success:function(result,status) {
                 console.log(result)
                 if(result.code==2003){
                   $('.phonemess').css('display','block')
                   $('.phonemess').text(result.msg)
                   $('.register').prop('disabled',true)
                 }else {
                   $('.phonemess').css('display','none')
                   $('.register').prop('disabled',false)
                 }
              }
          })
      })
      {#判断确认密码#}
      $('#inputPassword1').blur(function () {
        var psw=$('#inputPassword').val()
        var psw1=$('#inputPassword1').val()
        if(psw!=psw1){
          $('.pswmsg').css('display','inline')
        }else {
          $('.pswmsg').css('display','none')
        }

      })
    </script>
{%  endblock %}

Blog/templates/search.html
{%  extends 'base.html'  %}


{% block title %}搜索{% endblock %}

{% block css%}
    <style>
        .box{
            border-radius: 10px;
            border: 1px solid gray;
            margin-bottom: 10px;
            padding: 10px 30px;
        }
        .thum{
            font-size: 20px;
        }
        .user{
            float: left;
        }
        .like{
            float: right;
            cursor: pointer;

        }
        .clear{
            clear: both;
        }
    </style>
{% endblock %}

{%block body %}
<div class="container">

    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">


        {% for blog in blogs %}

            <div class="box">
                <h2 class="title">
                    <a href="#">{{blog.title}}</a>
                </h2>
                <p class="thum">{{blog.thum_content}}</p>
                <div class="user_like">
                    <div class="user">
                         <span>用户名：{{blog.user.username}}</span>
                    </div>

                    <div class="like"  >
                        {%if session.get('username')%}
<!--                            <a href="{{url_for('blog.likeorunlike')}}?bid={{blog.bid}}">-->
                            <a class="likea" bid="{{blog.bid}}" style="color: gray">
                        {%else%}
                            <a href="{{url_for('user.login')}}"    ></a>
                        {%endif%}
                           {%if blog.bid in like_bids %}
                            <span class="glyphicon glyphicon-thumbs-up likehand" style="color: red"></span>
                           {%else%}
                            <span class="glyphicon glyphicon-thumbs-up likehand" ></span>
                           {%endif%}
                        {#点赞的数量，点赞的用户个数 |length #}
                            <span class="likenum">{{blog.like_users|length}}</span>
                       </a>
                    </div>

                </div>
                <div class="clear"></div>

            </div>

        {% endfor %}


</div>
{%endblock%}

{% block js %}
    <script>
        $('.likea').click(function () {
            // #局部刷新点赞
            var _this=$(this)
            $.ajax({
                url:"{{url_for('blog.likeorunlike')}}",
                type:'get',
                data:'bid='+_this.attr('bid'),
                success: function (result,status) {
                    if(status=='success'){
                        _this.find('.likenum').text(result.likenum)
                        if(result.code==200){
                            _this.find('.likehand').css('color','red')

                        }else {
                             _this.find('.likehand').css('color','gray')
                        }
                    }

                }
            })
        })
    </script>
<!--    <script>-->
<!--        $('.like').click(function () {-->
<!--            $.ajax({-->
<!--                url:"{{url_for('blog.like')}}",-->
<!--                type:'post',-->
<!--                data:'bid='+$('.like').attr('bid')+"&csrf_token="+$('.csrf_token').val(),-->
<!--                success: function (result,statue) {-->
<!--                    console.log(result);-->
<!--                }-->
<!--            })-->
<!--        })-->
<!--    </script>-->
{% endblock %}

Blog/templates/updateicon.html
{%  extends 'base.html'  %}


{% block title %}修改头像{% endblock %}

{%block body%}
    <div class="container">
        <form action="{{url_for('user.updateicon')}}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
            <div class="form-group">
                <label for="exampleInputFile">选择图片</label>
                <input type="file" id="exampleInputFile" name="icon">
                <img src="{{url_for('static', filename='icon/LenovoWallPaper.jpg')}}" width="150px" class="icoonimage">
            </div>
            <button type="submit" class="btn btn-default">上传头像</button>
        </form>
    </div>
{%endblock%}

{%block js %}
    <script>
        var inputfile=document.getElementById(('exampleInputFile'));
        inputfile.onchange=function () {
            var files=inputfile.files;
            var imgurl=window.URL.createObjectURL(files[0]);
            $('.icoonimage').attr('src',imgurl)

        }
    </script>
{%endblock%}